// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsksiftdqprvijbanaas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5za3NpZnRkcXBydmlqYmFuYWFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzY2MjEsImV4cCI6MjA1OTkxMjYyMX0.ZMRKCKjjbA6FMkuH0VY2nd3O-p9AfZHWQGv4BIsAcLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);